= Crowdin Maven Plugin

A command line tool to handle synchronization of the source code with translations made on Crowdin.

Maven plugin for crowdin (https://crowdin.com)


== Requirements

* Git is installed and configured properly.
* Have a valid Crowdin Project ID and its key.
* Maven 3.2.5+ is installed

== Configuration

Add the Following properties in the maven settings.xml (contact with admin of crowdin exo-platform-35 project to get project key and id):
[source,xml]
----
  <pluginGroups>
    <!-- ... -->
    <pluginGroup>org.exoplatform.translation.crowdin</pluginGroup>
    <!-- ... -->
  </pluginGroups>
  <!-- ... -->
  <profile>
    <id>crowdin</id>
    <properties>
      <exo.crowdin.project.id>exo-platform</exo.crowdin.project.id>
      <exo.crowdin.project.key>YOUR KEY</exo.crowdin.project.key> 
    </properties>
  </profile>
  <!-- ... -->
  <activeProfiles>
    <activeProfile>crowdin</activeProfile>
  </activeProfiles>
----

== Usage

Available goals are: *download-translations*, *update-sources*, *update-crowdin*, *init-crowdin*, *upload-translation*.

[cols="2*", options="header"]
|===
|Goal
|Description

|crowdin:download-translations
|Download translations archive from Crowdin (defaults to /target/translation.zip).

|crowdin:update-sources
|Update translations files in source project with translations from Crowdin (from the translations archive), commit and push.

Translations archive default location is */target/translations.zip*, and can be changed with the option *exo.crowdin.translationsArchivePath*.

The list of languages if calculated from the zip content by default. It can be changed through the langs property:
**`mvn crowdin:update-sources -Dlangs=en,fr,vi -Pcrowdin`**

Activate new language/properties file by activating ONLY the new language (for example : `-Dlangs=ru`) and set the `isActivate` property to true (`-DisActivate=true`).

dryRun option (`-DdryRun=true`) will not download the all.zip if it exists in /target/, and it doesn't push to github.

|crowdin:update-crowdin
|Update all translations from source project to Crowdin.

dryRun option (`-DdryRun=true`) will not upload files to crowdin.

|crowdin:upload-translation
|Update changes in projects' translation files to Crowdin. It uses the information provided in the properties files (upload-translation.properties and <exo-project>.properties files) under upload-translation folder to determine the projects and their translation files need to be updated (in the same convention as the plugin's crowdin.properties and <exo-project>.properties files).

dryRun option (`-DdryRun=true`) means no communication with Crowdin will be done; Default: false.
Useful to see the evolution of the process. Combined with maven debug option -X, displays actual Rest calls and XmlPath queries.

|crowdin:restore-translation
|Restore a Crowdin project's directory structure and translations from its zip file. This zip file should be built with 'Export Only Approved' and 'Don't Export Untranslated' options unchecked so it will backup the untranslated and all suggested translations (not only the approved ones) as they will need to be restored also. Since this zip contains the project's directory structure and all of its translations, it can be considered as a project's backup and should be rebuilt (with 'Build Fresh Package' under Crowdin's 'Downloads' tab) and kept safe before doing any activity that may mess up the project.

Can also be used to clone a Crowdin project from its zip file (by changing the project's API key to point to another project) - see How-tos.

If you want to decide what to be uploaded to Crowdin, you can: first run with 'Dprepare=true' option to get the plugin stops after preparing the extracted folder for you to modify, e.g to remove some languages or projects you don't want to upload. When you're done, let the plugin continues by running with '-Dcontinue=true' option, it will upload your modified folder instead of the original zip.

dryRun option (`-DdryRun=true`) means no communication with Crowdin will be done; Default: false.
Useful to see the evolution of the process. Combined with maven debug option -X, displays actual Rest calls and XmlPath queries.
|===

== Let's go deeper

* crowdin:update-sources

** for each language and each localization file declared in translations.properties file...
*** if the file is an XML file, convert the properties file from Crowdin to an XML file
*** use the english version (en) as a skeleton and fill it with translations from Crowdin in the given language
*** save the filled file at its source location
*** commit the changes
*** if not in dry run, push the changes in the current branch

* crowdin:update-crowdin

** load the translations file of the project
** browse them to identify master files and translations
** create new folders, upload new master files and translations (new entries in the properties)
** update master files content on Crowdin (add new keys, rename existing keys, delete keys)
** delete old folders and files (old entries in the properties and not exist in file system)

* crowdin:upload-translation

** Identify the list of projects need to be changed, put them into upload-translation.properties. Each entry is a key/value pair with key = <project name>-<version> and value = <path to project's description file>
** For each project create the project description file named <project>.properties. In this file provide the path to the project in the 'baseDir' property and list all the translation files need to be updated in the form of <path in Crowdin>=<path in source code>

== Resources

* http://code.google.com/p/rest-assured/wiki/Usage?ts=1317978378&updated=Usage#Example_1_-_JSON

* http://blog.jayway.com/2011/10/09/simple-parsing-of-complex-json-and-xml-documents-in-java/

* http://rest-assured.googlecode.com/svn/tags/1.6/apidocs/com/jayway/restassured/path/xml/XmlPath.html

* http://groovy.codehaus.org/Updating+XML+with+XmlSlurper

* http://maven.apache.org/developers/mojo-api-specification.html

* http://maven.apache.org/plugin-developers/common-bugs.html

* http://www.regexplanet.com/advanced/java/index.html

* http://docs.oracle.com/javase/6/docs/api/index.html

* http://int.exoplatform.org/portal/intranet/wiki/group/spaces/platform_team/Crowdin_Maven_Plugin_Developer_guide

* http://int.exoplatform.org/portal/intranet/wiki/group/spaces/platform_team/Crowdin_Maven_Plugin_User_Guide

